import {
  BookOpenIcon,
  SpeakerWaveIcon,
  AcademicCapIcon,
  GlobeAltIcon,
  SwatchIcon,
  HomeIcon,
} from "@heroicons/react/24/solid";

export const cardsData = [
  {
    id: "teacher",
    title: "For Teachers",
    icon: BookOpenIcon,
    bullets: [
      "1-on-1 Lesson Customization",
      "Curriculum-Aligned Content",
      "AI-Powered Feedbacks",
      "Student Summary Reports",
    ],
    roleId: 2,
    buttonText: "Start as an Online Tutor",
    buttonBgColor: "#10B981",
    buttonHoverBgColor: "#059669",
  },
  {
    id: "lecturer",
    title: "For Lecturers",
    icon: SpeakerWaveIcon,
    bullets: [
      "Course Outline Generator",
      "Bulk Grading Assistant",
      "Research Companion",
      "AI Student Feedback Tool",
      "Thesis Topic Advisor (coming soon)n",
    ],
    buttonText: "Try AI Teacha for Lecturers",
    buttonBgColor: "#F59E0B",
    roleId: 2,
    buttonHoverBgColor: "#D97706",
  },
  {
    id: "school",
    title: "For Schools",
    icon: AcademicCapIcon,
    bullets: [
      "Standardized Lesson Plans",
      "School-Level Analytics",
      "Teacher Onboarding Support",
      " Identify Struggling Students Early",
      " Offline AI (Coming Soon)",
    ],
    buttonText: "Register as a School",
    buttonBgColor: "#5c3cbb",
    roleId: 4,
    buttonHoverBgColor: "#4a2f99",
  },
  {
    id: "online-tutors",
    title: "For Online Tutors",
    icon: GlobeAltIcon,
    bullets: [
      "LIVE Classroom Capabilities",
      "Curriculum-Aligned Content for Distant Learning",
      "Realtime Student Performance Reporting",
      "Personalized Assessment & Feedback",
      "Multimodal Content Creation & Delivery",
      "24/7 AI Chat Support for Instant Study Aids",
      "AI-Powered CBT for Automated Tests & Exams",
    ],
    roleId: 2,
    buttonText: "Join as an Online Tutor",
    buttonBgColor: "#007BFF",
    buttonHoverBgColor: "#0056b3",
  },
  {
    id: "students",
    title: "For Students",
    icon: SwatchIcon,
    bullets: [
      "Personalized Study Paths with Adaptive Learning Modules.",
      "Instant Homework & Problem Solving",
      "Multimodal Learning Resources",
      "Learning Challenge Detection & Support",
      "24/7 AI Study Assistance with Zyra",
    ],
    roleId: 1,
    buttonText: "Start Learning with AiTeacha",
    buttonBgColor: "#28A745",
    buttonHoverBgColor: "#218838",
  },
  {
    id: "parents",
    title: "For Parents",
    icon: HomeIcon,
    bullets: [
      "Real-Time Progress Dashboards",
      "Personalized Learning Insights",
      "Automated Homework Assistance",
      "Early Intervention Alerts and Supports",
      "Engagement & Communication Hub",
    ],
    roleId: 3,
    buttonText: "Monitor My Child's Progress",
    buttonBgColor: "#FFC107",
    buttonHoverBgColor: "#E0A800",
  },
];
